### ISSUE TITLE
Thank you for filling the Asset Library gap for video (no Issue) 

### ISSUE THREAD

**Issue by smcnally** [tin2tin/Import_as_asset#2]
"Import As Asset" continues to deliver in Blender `3.5` as it has since `3.4-alpha`. I'm usually in the **VSE** and "Import As Asset" has smoothed my video workflows and opened up **Compositor**, **Node Editor**, and **Dope Sheet** making them much more approachable to me. Many thanks for creating and making it available.

**Comment by tin2tin** [comment]
Thank you for spending your time on writing to me. I tend to spend a lot of time coding add-on for the VSE no-one are using, so knowing that you're using one of them makes me very happy. Actually, I also tried to add thumbnail loading for movie clips in the asset browser, but the BF devs did not care about it and I abandoned it. I hope there be a GSOC person this year looking at how to handle vse-friendly files in the asset browser. Fingers crossed.

I thought there was a problem with the assets in `3.6`, but it turned out they switched off the filters for those file types. So, changing the filters, they show up again.

**Comment by smcnally** [comment]
I use https://github.com/tin2tin/open_vse_docs, have used 
https://github.com/tin2tin/MediaInfoExtractor and plan to use https://github.com/tin2tin/text_strip_to_speech https://github.com/tin2tin/subtitle_editor with a captioning / .srt extension for `VSCode` for work this week. Your code, features, and stars are all appreciated. Many thanks -

**Comment by smcnally** [comment]
> I thought there was a problem with the assets in `3.6`, but it turned out they switched off the filters for those file types. So, changing the filters, they show up again.

I'm just running into this now with `3.6`. I'll create a new Issue if I don't solve changing the filters.  

```RuntimeError: Operator bpy.ops.asset.mark.poll() Data-block does not support asset operations - must be a Material, Collection, Object, Pose Action, Node Group or World```

**Comment by tin2tin** [comment]
It seems to me that they have blocked off any use of the asset browser in combination with the VSE. I've tried to submit patches for drawing thumbnails in the asset browser for the VSE file types, but they were ignored. I posted about your finding here, but that was also ignored: https://blender.chat/channel/asset-project

**Comment by smcnally** [comment]
I appreciate your efforts. Round-tripping between VSE and Compositor was much smoother for me when video files were in the Asset Library. I'm back to embedding separate Compositor Scenes into VSE Scenes. Even this has unexpected behavior when I've got more than a few GeoNodes, so I'm rendering more frequently and inserting results directly into VSE Scenes -- not exactly "round-tripping."
